name = "SetEnums"
uuid = "187c2503-7656-4954-a2ef-882908ec45bf"
authors = ["Arik Heinss <arik.heinss@destatis.de>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
[compat]
julia = "1.10"
